# Generated by Django 5.2 on 2026-02-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_add_new_modules_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(
                choices=[
                    ('core', 'Core'),
                    ('crm', 'CRM'),
                    ('sales', 'Ventes'),
                    ('hr', 'Ressources Humaines'),
                    ('payroll', 'Paie'),
                    ('accounting', 'Comptabilité'),
                    ('inventory', 'Stocks'),
                    ('purchasing', 'Achats'),
                    ('recruitment', 'Recrutement'),
                    ('dashboard', 'Tableau de bord'),
                    ('notifications', 'Notifications'),
                ],
                max_length=20,
                verbose_name='Module',
            ),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(
                choices=[
                    ('core', 'Core'),
                    ('crm', 'CRM'),
                    ('sales', 'Ventes'),
                    ('hr', 'Ressources Humaines'),
                    ('payroll', 'Paie'),
                    ('accounting', 'Comptabilité'),
                    ('inventory', 'Stocks'),
                    ('purchasing', 'Achats'),
                    ('recruitment', 'Recrutement'),
                    ('dashboard', 'Tableau de bord'),
                    ('notifications', 'Notifications'),
                ],
                max_length=20,
                verbose_name='Module',
            ),
        ),
    ]
