# Generated by Django 5.2 on 2026-03-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_add_notifications_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(
                default=False, verbose_name='Doit changer le mot de passe'
            ),
        ),
    ]
