# Generated by Django 5.2 on 2026-02-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_fix_thousand_separator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'company_name',
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    'country_code',
                    models.CharField(
                        help_text='Code ISO du pays (MA, CI, SN, FR...)',
                        max_length=5,
                        verbose_name='Code pays',
                    ),
                ),
                (
                    'locale_pack',
                    models.CharField(
                        choices=[
                            ('MA', 'Maroc'),
                            ('OHADA', 'OHADA — Afrique francophone'),
                            ('FR', 'France'),
                        ],
                        max_length=10,
                        verbose_name='Pack de localisation',
                    ),
                ),
                (
                    'address_line1',
                    models.CharField(
                        blank=True, max_length=200, verbose_name='Adresse ligne 1'
                    ),
                ),
                (
                    'address_line2',
                    models.CharField(
                        blank=True, max_length=200, verbose_name='Adresse ligne 2'
                    ),
                ),
                (
                    'city',
                    models.CharField(blank=True, max_length=100, verbose_name='Ville'),
                ),
                (
                    'postal_code',
                    models.CharField(
                        blank=True, max_length=20, verbose_name='Code postal'
                    ),
                ),
                (
                    'country',
                    models.CharField(blank=True, max_length=100, verbose_name='Pays'),
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Téléphone'
                    ),
                ),
                (
                    'email',
                    models.EmailField(blank=True, max_length=254, verbose_name='Email'),
                ),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                (
                    'legal_id_1_label',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Label identifiant 1'
                    ),
                ),
                (
                    'legal_id_1_value',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Valeur identifiant 1'
                    ),
                ),
                (
                    'legal_id_2_label',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Label identifiant 2'
                    ),
                ),
                (
                    'legal_id_2_value',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Valeur identifiant 2'
                    ),
                ),
                (
                    'legal_id_3_label',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Label identifiant 3'
                    ),
                ),
                (
                    'legal_id_3_value',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Valeur identifiant 3'
                    ),
                ),
                (
                    'legal_id_4_label',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Label identifiant 4'
                    ),
                ),
                (
                    'legal_id_4_value',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Valeur identifiant 4'
                    ),
                ),
                (
                    'logo',
                    models.ImageField(
                        blank=True, null=True, upload_to='company/', verbose_name='Logo'
                    ),
                ),
                (
                    'bank_name',
                    models.CharField(blank=True, max_length=100, verbose_name='Banque'),
                ),
                (
                    'bank_account',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Compte bancaire'
                    ),
                ),
                (
                    'bank_swift',
                    models.CharField(
                        blank=True, max_length=20, verbose_name='Code SWIFT/BIC'
                    ),
                ),
                (
                    'setup_completed',
                    models.BooleanField(default=False, verbose_name='Setup terminé'),
                ),
                (
                    'setup_date',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Date du setup'
                    ),
                ),
                (
                    'is_locked',
                    models.BooleanField(
                        default=False,
                        help_text='Verrouillé après la première écriture comptable.',
                        verbose_name='Verrouillé',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
            ],
            options={
                'verbose_name': 'Configuration entreprise',
                'verbose_name_plural': 'Configurations entreprise',
            },
        ),
    ]
