# Generated by Django 5.2 on 2026-02-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_company_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'email_host',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=200,
                        verbose_name='Serveur SMTP',
                    ),
                ),
                (
                    'email_port',
                    models.PositiveIntegerField(default=587, verbose_name='Port'),
                ),
                (
                    'email_use_tls',
                    models.BooleanField(default=True, verbose_name='Utiliser TLS'),
                ),
                (
                    'email_host_user',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=200,
                        verbose_name='Utilisateur SMTP',
                    ),
                ),
                (
                    'email_host_password',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=200,
                        verbose_name='Mot de passe SMTP',
                    ),
                ),
                (
                    'default_from_email',
                    models.EmailField(
                        blank=True,
                        default='',
                        max_length=254,
                        verbose_name='Adresse expéditeur',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Configuration email',
                'verbose_name_plural': 'Configuration email',
            },
        ),
        migrations.RemoveField(
            model_name='coresettings',
            name='company',
        ),
    ]
