# Generated by Django 5.2 on 2026-02-28 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_create_document_sequences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
