# Generated by Django 5.2 on 2026-03-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_rename_locale_pack_to_accounting_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysetup',
            name='country_code',
            field=models.CharField(
                help_text='Code ISO du pays (MA, CI, SN, FR...)',
                max_length=5,
                verbose_name='Code pays',
            ),
        ),
    ]
