# Generated by Django 5.2 on 2026-02-28 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecruitmentNotification',
        ),
    ]
