# Generated by Django 5.2 on 2026-03-05 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0002_employee_dependent_children_employee_marital_status'),
        ('payroll', '0003_employee_contract_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(
                blank=True,
                help_text='Obligatoire pour les contrats à durée déterminée.',
                null=True,
                verbose_name='Date de fin de contrat',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(
                blank=True, null=True, verbose_name='Date de début de contrat'
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='employees',
                to='payroll.contracttype',
                verbose_name='Type de contrat',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(
                blank=True, null=True, verbose_name="Fin de période d'essai"
            ),
        ),
    ]
