# Generated by Django 5.2 on 2026-03-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0003_employee_contract_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                (
                    'target_audience',
                    models.CharField(
                        choices=[
                            ('all', 'Tous les employes'),
                            ('department', 'Par departement'),
                            ('individual', 'Individuel'),
                        ],
                        default='all',
                        max_length=20,
                        verbose_name='Audience cible',
                    ),
                ),
                (
                    'is_pinned',
                    models.BooleanField(default=False, verbose_name='Epingle'),
                ),
                (
                    'is_auto_generated',
                    models.BooleanField(
                        default=False, verbose_name='Genere automatiquement'
                    ),
                ),
                (
                    'expires_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Expire le'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Cree le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifie le'),
                ),
                (
                    'author',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='announcements',
                        to='hr.employee',
                        verbose_name='Auteur',
                    ),
                ),
                (
                    'target_departments',
                    models.ManyToManyField(
                        blank=True,
                        related_name='announcements',
                        to='hr.department',
                        verbose_name='Departements cibles',
                    ),
                ),
                (
                    'target_employees',
                    models.ManyToManyField(
                        blank=True,
                        related_name='targeted_announcements',
                        to='hr.employee',
                        verbose_name='Employes cibles',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
