# Generated by Django 5.2 on 2026-03-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0004_add_announcement_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCertificateRequest',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'purpose',
                    models.CharField(
                        choices=[
                            ('bank', 'Dossier bancaire'),
                            ('visa', 'Demande de visa'),
                            ('rental', 'Dossier de location'),
                            ('other', 'Autre'),
                        ],
                        default='other',
                        max_length=20,
                        verbose_name='Objet',
                    ),
                ),
                (
                    'purpose_detail',
                    models.TextField(blank=True, verbose_name='Precisions'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'En attente'),
                            ('approved', 'Approuvee'),
                            ('rejected', 'Rejetee'),
                        ],
                        default='pending',
                        max_length=20,
                        verbose_name='Statut',
                    ),
                ),
                ('hr_notes', models.TextField(blank=True, verbose_name='Notes RH')),
                (
                    'pdf_file',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='Fichier PDF',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Demandee le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifiee le'),
                ),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='certificate_requests',
                        to='hr.employee',
                        verbose_name='Employe',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Demande d attestation de travail',
                'verbose_name_plural': 'Demandes d attestations de travail',
                'ordering': ['-created_at'],
            },
        ),
    ]
