# Generated by Django 5.2 on 2026-03-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0005_add_workcertificaterequest_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('harassment', 'Harcelement'),
                            ('discrimination', 'Discrimination'),
                            ('workload', 'Charge de travail'),
                            ('management', 'Comportement managerial'),
                            ('other', 'Autre'),
                        ],
                        max_length=20,
                        verbose_name='Categorie',
                    ),
                ),
                ('description', models.TextField(verbose_name='Description')),
                (
                    'is_anonymous',
                    models.BooleanField(default=False, verbose_name='Anonyme'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('open', 'Ouverte'),
                            ('investigating', 'En cours d investigation'),
                            ('resolved', 'Resolue'),
                            ('closed', 'Fermee'),
                        ],
                        default='open',
                        max_length=20,
                        verbose_name='Statut',
                    ),
                ),
                (
                    'hr_notes',
                    models.TextField(blank=True, verbose_name='Notes RH (prive)'),
                ),
                (
                    'resolution_notes',
                    models.TextField(blank=True, verbose_name='Notes de resolution'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'assigned_to',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='assigned_complaints',
                        to='hr.employee',
                        verbose_name='Assigne a (RH)',
                    ),
                ),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='complaints',
                        to='hr.employee',
                        verbose_name='Employe',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Doleance',
                'verbose_name_plural': 'Doleances',
                'ordering': ['-created_at'],
            },
        ),
    ]
