# Generated by Django 5.2 on 2026-03-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0006_add_complaint_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                (
                    'icon',
                    models.CharField(
                        blank=True,
                        help_text='Ex: TrophyOutlined, StarOutlined',
                        max_length=50,
                        verbose_name='Icone',
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de recompense',
                'verbose_name_plural': 'Types de recompenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('awarded_date', models.DateField(verbose_name='Date d attribution')),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Commentaire'),
                ),
                (
                    'is_public',
                    models.BooleanField(
                        default=True, verbose_name='Visible sur le reward board'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'awarded_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='rewards_given',
                        to='hr.employee',
                        verbose_name='Attribue par',
                    ),
                ),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rewards',
                        to='hr.employee',
                        verbose_name='Employe',
                    ),
                ),
                (
                    'reward_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='rewards',
                        to='hr.rewardtype',
                        verbose_name='Type de recompense',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Recompense',
                'verbose_name_plural': 'Recompenses',
                'ordering': ['-awarded_date'],
            },
        ),
    ]
