# Generated by Django 5.2 on 2026-03-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0012_register_carry_over_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='pdf_file',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Fichier PDF'
            ),
        ),
    ]
