# Generated by Django 5.2 on 2026-02-25 09:39

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('sales', '0005_add_invoice_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                (
                    'code',
                    models.CharField(max_length=20, unique=True, verbose_name='Code'),
                ),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                (
                    'is_default',
                    models.BooleanField(default=False, verbose_name='Par défaut'),
                ),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                (
                    'code',
                    models.CharField(max_length=20, unique=True, verbose_name='Code'),
                ),
                (
                    'accounting_account',
                    models.ForeignKey(
                        blank=True,
                        help_text='Compte comptable de stock associé (classe 3)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='accounting.account',
                        verbose_name='Compte comptable de stock',
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='children',
                        to='inventory.productcategory',
                        verbose_name='Catégorie parente',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockInventory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'reference',
                    models.CharField(
                        max_length=50, unique=True, verbose_name='Référence'
                    ),
                ),
                ('date', models.DateField(verbose_name='Date')),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('draft', 'Brouillon'),
                            ('in_progress', 'En cours'),
                            ('validated', 'Validé'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='État',
                    ),
                ),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                (
                    'validated_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Validé le'
                    ),
                ),
                (
                    'validated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='validated_inventories',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Validé par',
                    ),
                ),
                (
                    'warehouse',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='inventories',
                        to='inventory.warehouse',
                        verbose_name='Entrepôt',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockInventoryLine',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'theoretical_qty',
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=15,
                        verbose_name='Quantité théorique',
                    ),
                ),
                (
                    'physical_qty',
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=15,
                        verbose_name='Quantité physique',
                    ),
                ),
                (
                    'difference',
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F('physical_qty'), '-', models.F('theoretical_qty')
                        ),
                        output_field=models.DecimalField(
                            decimal_places=3, max_digits=15
                        ),
                    ),
                ),
                (
                    'inventory',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lines',
                        to='inventory.stockinventory',
                        verbose_name='Inventaire',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='sales.product',
                        verbose_name='Produit',
                    ),
                ),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'move_type',
                    models.CharField(
                        choices=[
                            ('IN', 'Entrée'),
                            ('OUT', 'Sortie'),
                            ('TRANSFER', 'Transfert'),
                            ('ADJUST', 'Ajustement inventaire'),
                            ('RETURN_IN', 'Retour client'),
                            ('RETURN_OUT', 'Retour fournisseur'),
                        ],
                        max_length=20,
                        verbose_name='Type de mouvement',
                    ),
                ),
                (
                    'quantity',
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name='Quantité'
                    ),
                ),
                (
                    'unit_cost',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name='Coût unitaire',
                    ),
                ),
                (
                    'reference',
                    models.CharField(
                        blank=True,
                        help_text='N° BC, BL, facture...',
                        max_length=100,
                        verbose_name='Référence',
                    ),
                ),
                (
                    'source_document_type',
                    models.CharField(
                        blank=True,
                        help_text='order, invoice, purchase...',
                        max_length=50,
                        verbose_name='Type document source',
                    ),
                ),
                (
                    'source_document_id',
                    models.IntegerField(
                        blank=True, null=True, verbose_name='ID document source'
                    ),
                ),
                ('date', models.DateTimeField(verbose_name='Date du mouvement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Créé par',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='stock_moves',
                        to='sales.product',
                        verbose_name='Produit',
                    ),
                ),
                (
                    'warehouse',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='stock_moves',
                        to='inventory.warehouse',
                        verbose_name='Entrepôt',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'quantity_on_hand',
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name='Quantité en stock',
                    ),
                ),
                (
                    'quantity_reserved',
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name='Quantité réservée',
                    ),
                ),
                (
                    'quantity_available',
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F('quantity_on_hand'),
                            '-',
                            models.F('quantity_reserved'),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=3, max_digits=15
                        ),
                    ),
                ),
                (
                    'last_updated',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Dernière mise à jour'
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='stock_levels',
                        to='sales.product',
                        verbose_name='Produit',
                    ),
                ),
                (
                    'warehouse',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='stock_levels',
                        to='inventory.warehouse',
                        verbose_name='Entrepôt',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Niveau de stock',
                'verbose_name_plural': 'Niveaux de stock',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
