# Generated by Django 5.2 on 2026-03-01 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_move_productcategory_to_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='content_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='contenttypes.contenttype',
                verbose_name='Type de document source',
            ),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='object_id',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='ID document source'
            ),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='source_document_id',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='ID document source (legacy)'
            ),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='source_document_type',
            field=models.CharField(
                blank=True,
                help_text='Champ legacy — sera supprimé après migration',
                max_length=50,
                verbose_name='Type document source (legacy)',
            ),
        ),
    ]
