# Generated by Django 5.2 on 2026-03-01 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0004_ic013_step2_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmove',
            name='source_document_id',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='source_document_type',
        ),
    ]
