# Generated by Django 5.2 on 2026-03-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0002_ic010_add_international_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='requires_end_date',
            field=models.BooleanField(
                default=False,
                help_text='Si activé, la date de fin de contrat est requise pour les employés avec ce type.',
                verbose_name='Date de fin obligatoire',
            ),
        ),
    ]
