# Generated by Django 5.2 on 2026-03-08 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0004_set_requires_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayroll',
            name='cnss_number',
            field=models.CharField(
                blank=True, max_length=30, verbose_name='N° immatriculation sociale'
            ),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='amo_employee',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name='Cotisation complémentaire salariale',
            ),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='amo_employer',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name='Cotisation complémentaire patronale',
            ),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='cnss_employee',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name='Cotisation sociale salariale',
            ),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='cnss_employer',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name='Cotisation sociale patronale',
            ),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='income_tax',
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name='Impôt sur le revenu'
            ),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='is_cnss_eligible',
            field=models.BooleanField(
                default=True, verbose_name='Soumis cotisations sociales'
            ),
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name='Montant'
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
                (
                    'component',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='payroll.salarycomponent',
                        verbose_name='Composant',
                    ),
                ),
                (
                    'employee_payroll',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='allowances',
                        to='payroll.employeepayroll',
                        verbose_name='Données de paie',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Prime / Indemnité employé',
                'verbose_name_plural': 'Primes / Indemnités employés',
                'ordering': ['component__code'],
                'unique_together': {('employee_payroll', 'component')},
            },
        ),
    ]
