# Generated by Django 5.2 on 2026-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0005_add_employee_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponent',
            name='base_rule',
            field=models.CharField(
                blank=True,
                choices=[
                    ('gross', 'Brut total'),
                    ('capped', 'Brut plafonné'),
                    ('taxable', 'Imposable'),
                    ('fixed', 'Montant fixe'),
                ],
                default='fixed',
                max_length=20,
                verbose_name='Règle de base',
            ),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='cap_parameter_code',
            field=models.CharField(
                blank=True,
                help_text='Code PayrollParameter pour le plafond (si base_rule=capped)',
                max_length=50,
                verbose_name='Code paramètre plafond',
            ),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('earnings', 'Gains'),
                    ('social_employee', 'Cotisation sociale salariale'),
                    ('social_employer', 'Cotisation sociale patronale'),
                    ('health_employee', 'Cotisation santé salariale'),
                    ('health_employer', 'Cotisation santé patronale'),
                    ('tax', 'Impôt'),
                    ('other_deduction', 'Autre retenue salariale'),
                    ('other_employer', 'Autre charge patronale'),
                ],
                default='earnings',
                max_length=30,
                verbose_name='Catégorie',
            ),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='default_display_order',
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Ordre d'affichage par défaut"
            ),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='rate_parameter_code',
            field=models.CharField(
                blank=True,
                help_text='Code PayrollParameter pour résoudre le taux dynamiquement',
                max_length=50,
                verbose_name='Code paramètre taux',
            ),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
    ]
