# Generated by Django 5.2 on 2026-03-26 16:55

from django.db import migrations


def backfill_employee_payroll(apps, schema_editor):
    """
    Crée une fiche EmployeePayroll vide pour chaque employé qui n'en a pas encore.
    Pack-agnostique : priorité au contract_type de l'employé, fallback sur premier actif.
    Idempotente : skip si la fiche existe déjà.
    """
    import logging

    logger = logging.getLogger(__name__)

    Employee = apps.get_model('hr', 'Employee')
    EmployeePayroll = apps.get_model('payroll', 'EmployeePayroll')
    ContractType = apps.get_model('payroll', 'ContractType')

    for employee in Employee.objects.all():
        if EmployeePayroll.objects.filter(employee=employee).exists():
            continue

        contract_type = None
        if employee.contract_type_id:
            contract_type = ContractType.objects.filter(
                pk=employee.contract_type_id, is_active=True
            ).first()
        if contract_type is None:
            contract_type = ContractType.objects.filter(is_active=True).first()

        if contract_type is None:
            logger.warning(
                f'backfill_employee_payroll : aucun ContractType actif — '
                f'EmployeePayroll non créé pour {employee}'
            )
            continue

        EmployeePayroll.objects.create(
            employee=employee,
            contract_type=contract_type,
            base_salary=0,
            payment_method='bank_transfer',
        )


def reverse_backfill_employee_payroll(apps, schema_editor):
    """
    Supprime uniquement les fiches créées par ce backfill (salaire de base = 0).
    Les fiches avec un salaire > 0 sont conservées.
    """
    EmployeePayroll = apps.get_model('payroll', 'EmployeePayroll')
    EmployeePayroll.objects.filter(base_salary=0).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0007_employee_classification'),
    ]

    operations = [
        migrations.RunPython(
            backfill_employee_payroll,
            reverse_code=reverse_backfill_employee_payroll,
        ),
    ]
