# Generated by Django 5.2 on 2026-03-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0008_backfill_employee_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayroll',
            name='cimr_number',
            field=models.CharField(
                blank=True,
                help_text='Caisse Interprofessionnelle Marocaine de Retraites (Maroc)',
                max_length=30,
                verbose_name='N° C.I.M.R',
            ),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='health_insurance_number',
            field=models.CharField(
                blank=True,
                help_text='Numéro assurance maladie complémentaire (Maroc)',
                max_length=30,
                verbose_name='N° Assurance Maladie',
            ),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='igr_parts',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Nombre de parts pour le calcul fiscal (Côte d'Ivoire)",
                null=True,
                verbose_name='Parts IGR',
            ),
        ),
    ]
