# Generated by Django 5.2 on 2025-05-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(
                choices=[
                    ('website', 'Website'),
                    ('referral', 'Referral'),
                    ('cold_call', 'Cold Call'),
                    ('social', 'Social Media'),
                    ('email', 'Email Campaign'),
                    ('chatbot', 'Chatbot IA'),
                    ('event', 'Event/Conference'),
                    ('other', 'Other'),
                ],
                default='website',
                max_length=20,
            ),
        ),
    ]
