# Generated by Django 5.2 on 2026-04-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0003_opportunity_currency_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(
                blank=True,
                default='',
                help_text='NCC (CI), ICE (MA), SIREN (FR)',
                max_length=50,
                verbose_name='Identifiant fiscal',
            ),
        ),
    ]
