# Generated by Django 5.2 on 2026-02-25 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0003_company_setup'),
        ('crm', '0002_alter_contact_source'),
        ('inventory', '0001_initial'),
        ('sales', '0006_add_stock_fields_to_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'number',
                    models.CharField(max_length=50, unique=True, verbose_name='Numéro'),
                ),
                ('date', models.DateField(verbose_name='Date de commande')),
                (
                    'expected_delivery_date',
                    models.DateField(
                        blank=True, null=True, verbose_name='Date de livraison prévue'
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('draft', 'Brouillon'),
                            ('confirmed', 'Confirmé'),
                            ('received', 'Réceptionné'),
                            ('invoiced', 'Facturé'),
                            ('cancelled', 'Annulé'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='État',
                    ),
                ),
                (
                    'subtotal',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Sous-total HT',
                    ),
                ),
                (
                    'tax_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Montant TVA',
                    ),
                ),
                (
                    'total',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Total TTC',
                    ),
                ),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Créé par',
                    ),
                ),
                (
                    'currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='core.currency',
                        verbose_name='Devise',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Bon de commande fournisseur',
                'verbose_name_plural': 'Bons de commande fournisseur',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True, max_length=300, verbose_name='Description'
                    ),
                ),
                (
                    'quantity',
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name='Quantité'
                    ),
                ),
                (
                    'unit_price',
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name='Prix unitaire HT'
                    ),
                ),
                (
                    'tax_rate',
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name='Taux TVA (%)',
                    ),
                ),
                (
                    'quantity_received',
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name='Quantité reçue',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='purchasing.purchaseorder',
                        verbose_name='Bon de commande',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='sales.product',
                        verbose_name='Produit',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ligne de commande fournisseur',
                'verbose_name_plural': 'Lignes de commande fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'number',
                    models.CharField(max_length=50, unique=True, verbose_name='Numéro'),
                ),
                ('date', models.DateField(verbose_name='Date de réception')),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('draft', 'Brouillon'),
                            ('validated', 'Validé'),
                            ('cancelled', 'Annulé'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='État',
                    ),
                ),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                (
                    'validated_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Validé le'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_receptions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Créé par',
                    ),
                ),
                (
                    'purchase_order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='receptions',
                        to='purchasing.purchaseorder',
                        verbose_name='Bon de commande',
                    ),
                ),
                (
                    'validated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='validated_receptions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Validé par',
                    ),
                ),
                (
                    'warehouse',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='inventory.warehouse',
                        verbose_name='Entrepôt',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Réception',
                'verbose_name_plural': 'Réceptions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'quantity_received',
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name='Quantité reçue'
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='sales.product',
                        verbose_name='Produit',
                    ),
                ),
                (
                    'purchase_order_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='reception_items',
                        to='purchasing.purchaseorderitem',
                        verbose_name='Ligne de commande',
                    ),
                ),
                (
                    'reception',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='purchasing.reception',
                        verbose_name='Réception',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ligne de réception',
                'verbose_name_plural': 'Lignes de réception',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                (
                    'code',
                    models.CharField(max_length=20, unique=True, verbose_name='Code'),
                ),
                (
                    'contact_name',
                    models.CharField(
                        blank=True, max_length=200, verbose_name='Nom du contact'
                    ),
                ),
                (
                    'email',
                    models.EmailField(blank=True, max_length=254, verbose_name='Email'),
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Téléphone'
                    ),
                ),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                (
                    'tax_id',
                    models.CharField(
                        blank=True,
                        help_text='ICE, IF, RC…',
                        max_length=50,
                        verbose_name='Identifiant fiscal',
                    ),
                ),
                (
                    'payment_terms',
                    models.IntegerField(
                        default=30, verbose_name='Délai de paiement (jours)'
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        blank=True,
                        help_text='Lien optionnel vers le CRM',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='supplier_profile',
                        to='crm.company',
                        verbose_name='Entreprise CRM',
                    ),
                ),
                (
                    'currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='core.currency',
                        verbose_name='Devise',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='purchase_orders',
                to='purchasing.supplier',
                verbose_name='Fournisseur',
            ),
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'number',
                    models.CharField(max_length=50, unique=True, verbose_name='Numéro'),
                ),
                (
                    'supplier_reference',
                    models.CharField(
                        blank=True,
                        help_text='Numéro de facture du fournisseur',
                        max_length=100,
                        verbose_name='Référence fournisseur',
                    ),
                ),
                ('date', models.DateField(verbose_name='Date de facture')),
                (
                    'due_date',
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('draft', 'Brouillon'),
                            ('validated', 'Validée'),
                            ('paid', 'Payée'),
                            ('cancelled', 'Annulée'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='État',
                    ),
                ),
                (
                    'subtotal',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Sous-total HT',
                    ),
                ),
                (
                    'tax_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Montant TVA',
                    ),
                ),
                (
                    'total',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Total TTC',
                    ),
                ),
                (
                    'amount_paid',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Montant payé',
                    ),
                ),
                (
                    'amount_due',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Montant dû',
                    ),
                ),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Créé par',
                    ),
                ),
                (
                    'currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='core.currency',
                        verbose_name='Devise',
                    ),
                ),
                (
                    'journal_entry',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='supplier_invoices',
                        to='accounting.journalentry',
                        verbose_name='Écriture comptable',
                    ),
                ),
                (
                    'purchase_order',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='supplier_invoices',
                        to='purchasing.purchaseorder',
                        verbose_name='Bon de commande',
                    ),
                ),
                (
                    'supplier',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='invoices',
                        to='purchasing.supplier',
                        verbose_name='Fournisseur',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Facture fournisseur',
                'verbose_name_plural': 'Factures fournisseur',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True, max_length=300, verbose_name='Description'
                    ),
                ),
                (
                    'quantity',
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name='Quantité'
                    ),
                ),
                (
                    'unit_price',
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name='Prix unitaire HT'
                    ),
                ),
                (
                    'tax_rate',
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name='Taux TVA (%)',
                    ),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='purchasing.supplierinvoice',
                        verbose_name='Facture fournisseur',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='sales.product',
                        verbose_name='Produit',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ligne de facture fournisseur',
                'verbose_name_plural': 'Lignes de facture fournisseur',
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField(verbose_name='Date de paiement')),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name='Montant'
                    ),
                ),
                (
                    'method',
                    models.CharField(
                        choices=[
                            ('bank_transfer', 'Virement bancaire'),
                            ('check', 'Chèque'),
                            ('cash', 'Espèces'),
                            ('lcn', 'LCN'),
                            ('other', 'Autre'),
                        ],
                        default='bank_transfer',
                        max_length=20,
                        verbose_name='Mode de paiement',
                    ),
                ),
                (
                    'reference',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Référence'
                    ),
                ),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Créé par',
                    ),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='payments',
                        to='purchasing.supplierinvoice',
                        verbose_name='Facture fournisseur',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': 'Paiements fournisseur',
                'ordering': ['-date'],
            },
        ),
    ]
