# Generated by Django 5.2 on 2026-02-25 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='credit_note_reason',
            field=models.TextField(
                blank=True, default='', verbose_name="Motif de l'avoir"
            ),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='parent_invoice',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='credit_notes',
                to='purchasing.supplierinvoice',
                verbose_name="Facture d'origine",
            ),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='type',
            field=models.CharField(
                choices=[
                    ('standard', 'Standard'),
                    ('credit_note', 'Avoir fournisseur'),
                ],
                default='standard',
                max_length=20,
                verbose_name='Type',
            ),
        ),
    ]
