# Generated by Django 5.2 on 2026-02-26 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('purchasing', '0002_add_credit_note_fields_to_supplier_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoiceDocument',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        upload_to='purchasing/invoices/%Y/%m/', verbose_name='Fichier'
                    ),
                ),
                (
                    'filename',
                    models.CharField(max_length=255, verbose_name='Nom du fichier'),
                ),
                (
                    'file_size',
                    models.PositiveIntegerField(
                        default=0, verbose_name='Taille (octets)'
                    ),
                ),
                (
                    'mime_type',
                    models.CharField(
                        default='application/pdf',
                        max_length=100,
                        verbose_name='Type MIME',
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True, max_length=300, verbose_name='Description'
                    ),
                ),
                (
                    'uploaded_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Date de téléversement'
                    ),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='documents',
                        to='purchasing.supplierinvoice',
                        verbose_name='Facture fournisseur',
                    ),
                ),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Téléversé par',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Pièce jointe facture fournisseur',
                'verbose_name_plural': 'Pièces jointes factures fournisseur',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
