# Generated by Django 5.2 on 2026-02-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('purchasing', '0003_supplier_invoice_document'),
        ('sales', '0006_add_stock_fields_to_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('quantity__gt', 0)),
                name='purchasing_purchaseorderitem_quantity_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)),
                name='purchasing_purchaseorderitem_tax_rate_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('quantity__gt', 0)),
                name='purchasing_supplierinvoiceitem_quantity_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)),
                name='purchasing_supplierinvoiceitem_tax_rate_range',
            ),
        ),
    ]
