# Generated by Django 5.2 on 2026-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'purchasing',
            '0004_purchaseorderitem_purchasing_purchaseorderitem_quantity_positive_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='tax_rate',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name='Taux TVA (%)'
            ),
        ),
        migrations.AlterField(
            model_name='supplierinvoiceitem',
            name='tax_rate',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name='Taux TVA (%)'
            ),
        ),
    ]
