# Generated by Django 5.2 on 2026-02-28 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
        ('purchasing', '0006_move_product_fk_to_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='catalog.product',
                verbose_name='Produit',
            ),
        ),
        migrations.AlterField(
            model_name='receptionitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='catalog.product',
                verbose_name='Produit',
            ),
        ),
        migrations.AlterField(
            model_name='supplierinvoiceitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='catalog.product',
                verbose_name='Produit',
            ),
        ),
    ]
