# Generated by Django 5.2 on 2026-03-25 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
        ('purchasing', '0007_alter_purchaseorderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoiceitem',
            name='product',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='catalog.product',
                verbose_name='Produit',
            ),
        ),
    ]
