# Generated by Django 5.2 on 2025-05-16 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0002_alter_contact_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                (
                    'code',
                    models.CharField(max_length=10, unique=True, verbose_name='Code'),
                ),
                (
                    'is_debit',
                    models.BooleanField(
                        default=True, verbose_name='Solde débiteur par défaut'
                    ),
                ),
                ('sequence', models.IntegerField(default=10, verbose_name='Séquence')),
            ],
            options={
                'verbose_name': 'Type de compte',
                'verbose_name_plural': 'Types de comptes',
                'ordering': ['sequence', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('draft', 'Brouillon'),
                            ('open', 'Ouvert'),
                            ('closed', 'Clôturé'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='État',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Exercice fiscal',
                'verbose_name_plural': 'Exercices fiscaux',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(max_length=20, unique=True, verbose_name='Code'),
                ),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                (
                    'is_reconcilable',
                    models.BooleanField(default=False, verbose_name='Lettrable'),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                (
                    'is_tax_account',
                    models.BooleanField(default=False, verbose_name='Compte de taxe'),
                ),
                (
                    'tax_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('vat_collected', 'TVA collectée'),
                            ('vat_deductible', 'TVA déductible'),
                            ('vat_import', "TVA à l'importation"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name='Type de taxe',
                    ),
                ),
                (
                    'tax_rate',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name='Taux de taxe',
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
                (
                    'parent_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='children',
                        to='accounting.account',
                        verbose_name='Compte parent',
                    ),
                ),
                (
                    'type_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='accounts',
                        to='accounting.accounttype',
                        verbose_name='Type de compte',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticAccount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(max_length=20, unique=True, verbose_name='Code'),
                ),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                (
                    'parent_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='children',
                        to='accounting.analyticaccount',
                        verbose_name='Compte parent',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Compte analytique',
                'verbose_name_plural': 'Comptes analytiques',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                (
                    'method',
                    models.CharField(
                        choices=[('linear', 'Linéaire'), ('degressive', 'Dégressif')],
                        default='linear',
                        max_length=20,
                        verbose_name="Méthode d'amortissement",
                    ),
                ),
                ('duration_years', models.IntegerField(verbose_name='Durée (années)')),
                (
                    'account_asset_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='asset_categories',
                        to='accounting.account',
                        verbose_name="Compte d'immobilisation",
                    ),
                ),
                (
                    'account_depreciation_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='depreciation_categories',
                        to='accounting.account',
                        verbose_name="Compte d'amortissement",
                    ),
                ),
                (
                    'account_expense_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='expense_categories',
                        to='accounting.account',
                        verbose_name='Compte de charges',
                    ),
                ),
            ],
            options={
                'verbose_name': "Catégorie d'immobilisation",
                'verbose_name_plural': "Catégories d'immobilisations",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                (
                    'code',
                    models.CharField(max_length=50, unique=True, verbose_name='Code'),
                ),
                (
                    'acquisition_date',
                    models.DateField(verbose_name="Date d'acquisition"),
                ),
                (
                    'acquisition_value',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Valeur d'acquisition",
                    ),
                ),
                (
                    'salvage_value',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Valeur résiduelle',
                    ),
                ),
                (
                    'method',
                    models.CharField(
                        blank=True,
                        choices=[('linear', 'Linéaire'), ('degressive', 'Dégressif')],
                        max_length=20,
                        null=True,
                        verbose_name="Méthode d'amortissement",
                    ),
                ),
                (
                    'duration_years',
                    models.IntegerField(
                        blank=True, null=True, verbose_name='Durée (années)'
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('draft', 'Brouillon'),
                            ('open', 'En cours'),
                            ('close', 'Clôturé'),
                            ('sold', 'Cédé'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='État',
                    ),
                ),
                (
                    'first_depreciation_date',
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de début d'amortissement",
                    ),
                ),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
                (
                    'category_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='assets',
                        to='accounting.assetcategory',
                        verbose_name='Catégorie',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Immobilisation',
                'verbose_name_plural': 'Immobilisations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('draft', 'Brouillon'),
                            ('open', 'Ouvert'),
                            ('closed', 'Clôturé'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='État',
                    ),
                ),
                (
                    'fiscal_year',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='periods',
                        to='accounting.fiscalyear',
                        verbose_name='Exercice fiscal',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Période fiscale',
                'verbose_name_plural': 'Périodes fiscales',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(max_length=10, unique=True, verbose_name='Code'),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('sale', 'Ventes'),
                            ('purchase', 'Achats'),
                            ('cash', 'Caisse'),
                            ('bank', 'Banque'),
                            ('general', 'Opérations diverses'),
                            ('situation', 'Situation'),
                        ],
                        max_length=20,
                        verbose_name='Type',
                    ),
                ),
                (
                    'sequence_id',
                    models.CharField(
                        default='YYYY/####', max_length=50, verbose_name='Séquence'
                    ),
                ),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                (
                    'default_credit_account_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='credit_journals',
                        to='accounting.account',
                        verbose_name='Compte de crédit par défaut',
                    ),
                ),
                (
                    'default_debit_account_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='debit_journals',
                        to='accounting.account',
                        verbose_name='Compte de débit par défaut',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('date', models.DateField(verbose_name='Date')),
                (
                    'reference',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Référence'
                    ),
                ),
                (
                    'balance_start',
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name='Solde initial'
                    ),
                ),
                (
                    'balance_end',
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name='Solde final'
                    ),
                ),
                (
                    'balance_end_real',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name='Solde final réel',
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('draft', 'Brouillon'),
                            ('open', 'En cours'),
                            ('confirm', 'Confirmé'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='État',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='bank_statements',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Créé par',
                    ),
                ),
                (
                    'journal_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='bank_statements',
                        to='accounting.journal',
                        verbose_name='Journal',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Relevé bancaire',
                'verbose_name_plural': 'Relevés bancaires',
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Numéro')),
                ('date', models.DateField(verbose_name='Date')),
                (
                    'ref',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Référence'
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('draft', 'Brouillon'),
                            ('posted', 'Validé'),
                            ('cancel', 'Annulé'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='État',
                    ),
                ),
                (
                    'source_module',
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name='Module source',
                    ),
                ),
                (
                    'source_model',
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name='Modèle source',
                    ),
                ),
                (
                    'source_id',
                    models.IntegerField(
                        blank=True, null=True, verbose_name='ID source'
                    ),
                ),
                ('narration', models.TextField(blank=True, verbose_name='Libellé')),
                (
                    'is_manual',
                    models.BooleanField(default=True, verbose_name='Saisie manuelle'),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='journal_entries',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Créé par',
                    ),
                ),
                (
                    'journal_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='entries',
                        to='accounting.journal',
                        verbose_name='Journal',
                    ),
                ),
                (
                    'period_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='entries',
                        to='accounting.fiscalperiod',
                        verbose_name='Période fiscale',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-date', '-id'],
                'unique_together': {('journal_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('sequence', models.IntegerField(verbose_name='Séquence')),
                ('date', models.DateField(verbose_name="Date d'amortissement")),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name='Montant'
                    ),
                ),
                (
                    'remaining_value',
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name='Valeur restante'
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('draft', 'Brouillon'),
                            ('posted', 'Comptabilisé'),
                            ('cancel', 'Annulé'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='État',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
                (
                    'asset_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='depreciation_lines',
                        to='accounting.asset',
                        verbose_name='Immobilisation',
                    ),
                ),
                (
                    'move_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='depreciation_lines',
                        to='accounting.journalentry',
                        verbose_name="Écriture d'amortissement",
                    ),
                ),
            ],
            options={
                'verbose_name': 'Dotation aux amortissements',
                'verbose_name_plural': 'Dotations aux amortissements',
                'ordering': ['asset_id', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='acquisition_move_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='acquired_assets',
                to='accounting.journalentry',
                verbose_name="Écriture d'acquisition",
            ),
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200, verbose_name='Libellé')),
                (
                    'debit',
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name='Débit'
                    ),
                ),
                (
                    'credit',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Crédit',
                    ),
                ),
                (
                    'amount_currency',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Montant en devise',
                    ),
                ),
                (
                    'date_maturity',
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    'is_reconciled',
                    models.BooleanField(default=False, verbose_name='Lettré'),
                ),
                (
                    'tax_base_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='Base de taxe',
                    ),
                ),
                (
                    'ref',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Référence'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
                (
                    'account_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='entry_lines',
                        to='accounting.account',
                        verbose_name='Compte',
                    ),
                ),
                (
                    'analytic_account_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='entry_lines',
                        to='accounting.analyticaccount',
                        verbose_name='Compte analytique',
                    ),
                ),
                (
                    'currency_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='journal_entry_lines',
                        to='core.currency',
                        verbose_name='Devise',
                    ),
                ),
                (
                    'entry_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lines',
                        to='accounting.journalentry',
                        verbose_name='Écriture',
                    ),
                ),
                (
                    'partner_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='journal_entry_lines',
                        to='crm.company',
                        verbose_name='Partenaire',
                    ),
                ),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écritures",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=200, verbose_name='Libellé')),
                (
                    'ref',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Référence'
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name='Montant'
                    ),
                ),
                (
                    'is_reconciled',
                    models.BooleanField(default=False, verbose_name='Rapproché'),
                ),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
                (
                    'partner_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='statement_lines',
                        to='crm.company',
                        verbose_name='Partenaire',
                    ),
                ),
                (
                    'statement_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lines',
                        to='accounting.bankstatement',
                        verbose_name='Relevé',
                    ),
                ),
                (
                    'journal_entry_line_ids',
                    models.ManyToManyField(
                        blank=True,
                        related_name='statement_lines',
                        to='accounting.journalentryline',
                        verbose_name="Lignes d'écritures",
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ligne de relevé',
                'verbose_name_plural': 'Lignes de relevé',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'account_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='reconciliations',
                        to='accounting.account',
                        verbose_name='Compte',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='reconciliations',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Créé par',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Lettrage',
                'verbose_name_plural': 'Lettrages',
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='reconciliation_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reconciled_lines',
                to='accounting.reconciliation',
                verbose_name='Lettrage',
            ),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name='Taux'
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('percent', 'Pourcentage'), ('fixed', 'Montant fixe')],
                        default='percent',
                        max_length=20,
                        verbose_name='Type',
                    ),
                ),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                (
                    'tax_category',
                    models.CharField(
                        choices=[
                            ('vat', 'TVA'),
                            ('vat_import', 'TVA importation'),
                            ('other', 'Autre'),
                        ],
                        default='vat',
                        max_length=20,
                        verbose_name='Catégorie',
                    ),
                ),
                (
                    'is_deductible',
                    models.BooleanField(default=False, verbose_name='Déductible'),
                ),
                (
                    'account_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='taxes',
                        to='accounting.account',
                        verbose_name='Compte de taxe',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Taxe',
                'verbose_name_plural': 'Taxes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='tax_line_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tax_lines',
                to='accounting.tax',
                verbose_name='Taxe',
            ),
        ),
    ]
