# Generated by Django 5.2 on 2026-03-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounting', '0003_add_bankstatement_source_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmapping',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
        ),
    ]
