# Generated by Django 5.2 on 2026-02-25 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'email_overdue_invoices',
                    models.BooleanField(
                        default=True, verbose_name='Email : factures échues'
                    ),
                ),
                (
                    'email_stock_alerts',
                    models.BooleanField(
                        default=True, verbose_name='Email : alertes stock'
                    ),
                ),
                (
                    'email_overdue_purchases',
                    models.BooleanField(
                        default=True, verbose_name='Email : achats en retard'
                    ),
                ),
                (
                    'in_app_enabled',
                    models.BooleanField(
                        default=True, verbose_name='Notifications in-app'
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notification_preferences',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'level',
                    models.CharField(
                        choices=[
                            ('info', 'Information'),
                            ('warning', 'Attention'),
                            ('critical', 'Critique'),
                            ('success', 'Succès'),
                        ],
                        default='info',
                        max_length=20,
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                (
                    'module',
                    models.CharField(
                        choices=[
                            ('sales', 'Ventes'),
                            ('purchasing', 'Achats'),
                            ('inventory', 'Stocks'),
                            ('hr', 'RH'),
                            ('payroll', 'Paie'),
                            ('accounting', 'Comptabilité'),
                            ('crm', 'CRM'),
                            ('recruitment', 'Recrutement'),
                            ('system', 'Système'),
                        ],
                        default='system',
                        max_length=50,
                    ),
                ),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'dedup_key',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Clé unique pour éviter les notifications en double',
                        max_length=200,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['user', 'is_read', '-created_at'],
                        name='notificatio_user_id_f2ad08_idx',
                    ),
                    models.Index(
                        fields=['dedup_key'], name='notificatio_dedup_k_f8363d_idx'
                    ),
                ],
            },
        ),
    ]
