# Generated by Django 5.2 on 2025-05-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_opportunity_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_tax_exempt',
            field=models.BooleanField(default=False, verbose_name='Exonéré de TVA'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_exemption_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Raison d'exonération"),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='has_deposit_invoice',
            field=models.BooleanField(default=False, verbose_name="A une facture d'acompte"),
        ),
        migrations.AddField(
            model_name='order',
            name='has_final_invoice',
            field=models.BooleanField(default=False, verbose_name='A une facture finale'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_tax_exempt',
            field=models.BooleanField(default=False, verbose_name='Exonéré de TVA'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_exemption_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Raison d'exonération"),
        ),
        migrations.AddField(
            model_name='quote',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_tax_exempt',
            field=models.BooleanField(default=False, verbose_name='Exonéré de TVA'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_exemption_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Raison d'exonération"),
        ),
    ]
