# Generated by Django 5.2 on 2025-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0003_add_tax_exemption_and_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(
                choices=[
                    ('standard', 'Standard'),
                    ('deposit', 'Acompte'),
                    ('final', 'Solde'),
                    ('credit', 'Avoir'),
                ],
                default='standard',
                max_length=20,
                verbose_name='Type de facture',
            ),
        ),
    ]
