# Generated by Django 5.2 on 2026-02-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0005_add_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name='Code-barres',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='inventory.productcategory',
                verbose_name='Catégorie',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(
                choices=[
                    ('stockable', 'Stockable'),
                    ('service', 'Service'),
                    ('consumable', 'Consommable'),
                ],
                default='stockable',
                max_length=20,
                verbose_name='Type de produit',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_alert_threshold',
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text='Seuil minimum déclenchant une alerte de réapprovisionnement',
                max_digits=15,
                verbose_name='Seuil alerte stock',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(
                default='unité', max_length=20, verbose_name='Unité de mesure'
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name='Poids (kg)',
            ),
        ),
    ]
