# Generated by Django 5.2 on 2026-02-28 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_settings_refactor_singleton'),
        ('crm', '0002_alter_contact_source'),
        ('inventory', '0001_initial'),
        ('sales', '0006_add_stock_fields_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.currency',
                verbose_name='Devise',
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bank_account',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='sales.bankaccount',
                verbose_name='Compte bancaire',
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='crm.company',
                verbose_name='Entreprise',
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='crm.contact',
                verbose_name='Contact',
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.currency',
                verbose_name='Devise',
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='opportunity',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='crm.opportunity',
                verbose_name='Opportunité',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='bank_account',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='sales.bankaccount',
                verbose_name='Compte bancaire',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='crm.company',
                verbose_name='Entreprise',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='crm.contact',
                verbose_name='Contact',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.currency',
                verbose_name='Devise',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='opportunity',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='crm.opportunity',
                verbose_name='Opportunité',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.currency',
                verbose_name='Devise',
            ),
        ),
        migrations.AlterField(
            model_name='quote',
            name='bank_account',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='sales.bankaccount',
                verbose_name='Compte bancaire',
            ),
        ),
        migrations.AlterField(
            model_name='quote',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='crm.company',
                verbose_name='Entreprise',
            ),
        ),
        migrations.AlterField(
            model_name='quote',
            name='contact',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='crm.contact',
                verbose_name='Contact',
            ),
        ),
        migrations.AlterField(
            model_name='quote',
            name='currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.currency',
                verbose_name='Devise',
            ),
        ),
        migrations.AlterField(
            model_name='quote',
            name='opportunity',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='crm.opportunity',
                verbose_name='Opportunité',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(
                condition=models.Q(('amount_paid__gte', 0)),
                name='sales_invoice_amount_paid_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('quantity__gt', 0)),
                name='sales_invoiceitem_quantity_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)),
                name='sales_invoiceitem_tax_rate_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('quantity__gt', 0)),
                name='sales_orderitem_quantity_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)),
                name='sales_orderitem_tax_rate_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(
                condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)),
                name='sales_product_tax_rate_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('quantity__gt', 0)),
                name='sales_quoteitem_quantity_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)),
                name='sales_quoteitem_tax_rate_range',
            ),
        ),
    ]
