# Generated by Django 5.2 on 2026-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0007_alter_bankaccount_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_rate',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name='Taux de TVA (%)',
            ),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tax_rate',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name='Taux de TVA (%)',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name='Taux de TVA (%)',
            ),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='tax_rate',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name='Taux de TVA (%)',
            ),
        ),
    ]
