# Generated by Django 5.2 on 2026-03-25 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_contact_optional_currency_on_items'),
        ('crm', '0003_opportunity_currency_to_fk'),
        ('sales', '0010_add_journal_entry_to_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='currency',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.currency',
                verbose_name='Devise',
            ),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.currency',
                verbose_name='Devise',
            ),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='currency',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.currency',
                verbose_name='Devise',
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='crm.contact',
                verbose_name='Contact',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='crm.contact',
                verbose_name='Contact',
            ),
        ),
        migrations.AlterField(
            model_name='quote',
            name='contact',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='crm.contact',
                verbose_name='Contact',
            ),
        ),
    ]
