# Generated by Django 5.2 on 2026-04-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0011_contact_optional_currency_on_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'mode',
                    models.CharField(
                        choices=[
                            ('disabled', 'Désactivé'),
                            ('simulation', 'Simulation'),
                            ('production', 'Production'),
                        ],
                        default='disabled',
                        max_length=20,
                        verbose_name='Mode',
                    ),
                ),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('auto', 'Automatique (selon le pack pays)'),
                            ('fne_ci', "FNE — Côte d'Ivoire"),
                            ('dgi_ma', 'DGI — Maroc'),
                            ('pdp_fr', 'PDP — France'),
                        ],
                        default='auto',
                        max_length=20,
                        verbose_name='Provider',
                    ),
                ),
                (
                    'api_url',
                    models.URLField(blank=True, default='', verbose_name='URL API'),
                ),
                (
                    'api_key',
                    models.CharField(
                        blank=True, default='', max_length=255, verbose_name='Clé API'
                    ),
                ),
                (
                    'establishment',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text="Nom de l'établissement (requis FNE CI)",
                        max_length=200,
                        verbose_name='Établissement',
                    ),
                ),
                (
                    'point_of_sale',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Nom du point de vente (requis FNE CI)',
                        max_length=200,
                        verbose_name='Point de vente',
                    ),
                ),
                (
                    'pdp_name',
                    models.CharField(
                        blank=True, default='', max_length=100, verbose_name='Nom PDP'
                    ),
                ),
                (
                    'pdp_api_url',
                    models.URLField(blank=True, default='', verbose_name='URL API PDP'),
                ),
                (
                    'pdp_client_id',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=255,
                        verbose_name='Client ID PDP',
                    ),
                ),
                (
                    'pdp_client_secret',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=255,
                        verbose_name='Client Secret PDP',
                    ),
                ),
                (
                    'reminder_enabled',
                    models.BooleanField(
                        default=True,
                        help_text='Notifier si des factures ne sont pas certifiées dans le délai',
                        verbose_name='Rappels activés',
                    ),
                ),
                (
                    'reminder_hours',
                    models.PositiveIntegerField(
                        default=24,
                        help_text='Délai en heures avant rappel de certification',
                        verbose_name='Délai de rappel (heures)',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
            ],
            options={
                'verbose_name': 'Configuration facturation électronique',
                'verbose_name_plural': 'Configurations facturation électronique',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_certified_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Date de certification e-facture'
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_external_id',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                verbose_name='ID externe e-facture',
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_raw_response',
            field=models.JSONField(
                blank=True, null=True, verbose_name='Réponse brute e-facture'
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_reference',
            field=models.CharField(
                blank=True,
                default='',
                max_length=100,
                verbose_name='Référence fiscale e-facture',
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_status',
            field=models.CharField(
                choices=[
                    ('not_applicable', 'Non applicable'),
                    ('pending', 'En attente'),
                    ('certified', 'Certifiée'),
                    ('simulated', 'Simulée'),
                    ('failed', 'Échec'),
                ],
                default='not_applicable',
                max_length=20,
                verbose_name='Statut e-facture',
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_verification_url',
            field=models.URLField(
                blank=True, default='', verbose_name='URL de vérification e-facture'
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(
                choices=[
                    ('bank_transfer', 'Virement bancaire'),
                    ('check', 'Chèque'),
                    ('cash', 'Espèces'),
                    ('credit_card', 'Carte de crédit'),
                    ('mobile_money', 'Mobile Money'),
                    ('deferred', 'Paiement à terme'),
                    ('other', 'Autre'),
                ],
                default='bank_transfer',
                max_length=20,
                verbose_name='Méthode de paiement',
            ),
        ),
    ]
